# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: ":shrug"
    replace: "¯\\_(ツ)_/¯"

  - trigger: ":meet"
    replace: "https://meet.google.com/ena-qpcg-ius?authuser=1"


  - trigger: ":pr-suggestion"
    replace: "**Sugestão Opcional:**\n\nX$|$\n\n> Pode resolver essa thread quando preferir!"

  - trigger: ":pr-compliment"
    replace: "**Elogio:**\n\nX$|$\n\n> Pode resolver essa thread depois de ler!"


  - trigger: ":jira-epic"
    replace: "**PARA ATINGIR:** \n\n- X$|$ \n\n**ENTREGAREMOS:** \n\n- X \n\n**CRITÉRIOS DE ACEITE:** \n\nFuncionais: \n- X \n\nNão-funcionais: \n- X \n\n**DÚVIDAS:** \n\n- X \n\n**REFERÊNCIAS:** \n\n- X"

  - trigger: ":jira-story"
    replace: "Eu, como X, quero conseguir Y para Z. \n\n**CRITÉRIOS DE ACEITE:** \n\nFuncionais: \n- X \n\nNão-funcionais: \n- X \n\n**DÚVIDAS:** \n\n- X \n\n**REFERÊNCIAS:** \n\n- X"

  - trigger: ":jira-spike"
    replace: "**O QUE QUEREMOS?** \n\n- X$|$ \n\n**POR QUE QUEREMOS?** \n\n- X \n\n**CRITÉRIOS DE ACEITE:** \n\nFuncionais: \n- X \n\nNão-funcionais: \n- X \n\n**TIMEBOX MÁXIMO:** \n\nX dias. \n\nPassado esse tempo, recomenda-se encerrar o spike com o que se descobriu até então. Logo após, defina os próximos spikes junto ao time para dar continuidade à investigação. \n\n**OUTPUT:** \n\n- Decisão tomada \n- Doc no Confluence ou repo \n- Apresentação ao time \n- Cards no Jira para endereçar os próximos passos \n\n**DÚVIDAS:** \n\n- X \n\n**REFERÊNCIAS:** \n\n- X"

  - trigger: ":jira-task"
    replace: "**CRITÉRIOS DE ACEITE:** \n\nFuncionais: \n- X \n\nNão-funcionais: \n- Logs (com level, timestamp, traceId etc) \n- Testes automatizados \n- Storybook \n- Documentação do repo (APIs e Arquitetura) atualizadas, se necessário \n- Infraestrutura como Código \n- Deploy para staging e production \n\n**DÚVIDAS:** \n\n- X \n\n**REFERÊNCIAS:** \n\n- X"

  - trigger: ":jira-debt"
    replace: "**CRITICIDADE**: \n\n1/5 -> Não crítico: não é uma melhoria, pois já deveria ter sido feito, mas precisa ser ajustado para manter o código limpo e fácil de ser extendido. \n\n2/5 -> Criticidade baixa: pode ser priorizado depois de uma release importante ou MVP, mas deveria ser priorizado antes da próxima entrega acontecer. \n\n3/5 -> Criticidade média: até pode esperar uma release importante ou entrega do MVP, mas vai custar bem mais caro ajustá-lo depois disso. \n\n4/5 -> Crítico: não pode esperar a release ou entrega do MVP acontecer, ou vamos nos arrepender amargamente por isso. \n\n5/5 -> Muito crítico: não é um incidente, mas pode se tornar um em breve, ou; uma bola de neve incontrolável de retrabalho, se não ajustado o quanto antes. \n\n**RESUMO:** \n\nPor não arrumarmos X, sofreremos Y. \n\nInsira um texto com detalhes não-técnicos aqui! \n\n**IMPACTO:** \n\nX \n\n**CRITÉRIOS DE ACEITE:** \n\nFuncionais: \n- X \n\nNão-funcionais: \n- Logs (com level, timestamp, traceId etc) \n- Testes automatizados \n- Storybook \n- Documentação do repo (APIs e Arquitetura) atualizadas, se necessário \n- Infraestrutura como Código \n- Deploy para staging e production \n\n**DÚVIDAS:** \n\n- X \n\n**REFERÊNCIAS:** \n\n- X"

  - trigger: ":jira-bug"
    replace: "**DESCRIÇÃO:** \n\nO problema X está acontecendo. \n\n**PASSOS P/ REPRODUZIR:** \n\n- X$|$ \n\n**CRITÉRIOS DE ACEITE:** \n\n- Logs (com level, timestamp, traceId etc) \n- Testes automatizados, ao menos para cobrir o bug \n- Storybook \n- Documentação do repo (APIs e Arquitetura) atualizadas, se necessário \n- Infraestrutura como Código \n- Deploy para staging e production \n\n**DÚVIDAS:** \n\n- X \n\n**REFERÊNCIAS:** \n\n- X"
