# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: ":pr-suggestion"
    replace: "**Sugestão Opcional:**\n\nX$|$\n\n> Pode resolver essa thread quando preferir!"

  - trigger: ":pr-compliment"
    replace: "**Elogio:**\n\nX$|$\n\n> Pode resolver essa thread depois de ler!"

  - trigger: ":shrug"
    replace: "¯\\_(ツ)_/¯"

  - trigger: ":jira-epic"
    replace: "*Entregável:* \n\n X \n\n *TODO:* \n\n- X \n\n *Dúvidas:* \n\n- X \n\n *Referências:* \n\n- X"

  - trigger: ":jira-story"
    replace: "Eu, como X, quero conseguir Y para Z. \n\n *Regras de negócio:* \n\n- X \n\n *Dúvidas:* \n\n- X \n\n *Referências:* \n\n- X"

  - trigger: ":jira-task"
    replace: "*Critérios de Aceite:* \n\n- Logs (com level, timestamp, traceId etc) \n- Testes automatizados \n- Storybook \n- Documentação do repo (APIs e Arquitetura) atualizadas, se necessário \n- Infraestrutura como Código \n- Deploy para staging e production \n\n *Dúvidas:* \n\n- X \n\n *Referências:* \n\n- X"

  - trigger: ":jira-spike"
    replace: "*O que queremos?* \n\n- X \n\n *TODO:* \n\n- X \n\n *Timebox máximo:* \n\n X dias. \n\n *Output:* \n\n- Decisão tomada \n- Doc no Confluence ou repo \n- Apresentação ao time \n- Cards no Jira para endereçar os próximos passos \n\n *Dúvidas:* \n\n- X \n\n *Referências:* \n\n- X"

  - trigger: ":jira-debt"
    replace: "*Impacto:* \n\n Criticidade: \n 1/5 -> Não crítico: não é uma melhoria, pois já deveria ter sido feito, mas precisa ser ajustado para manter o código limpo e fácil de ser extendido. \n 2/5 -> Criticidade baixa: pode ser priorizado depois de uma release importante ou MVP, mas deveria ser priorizado antes da próxima entrega acontecer. \n 3/5 -> Criticidade média: até pode esperar uma release importante ou entrega do MVP, mas vai custar bem mais caro ajustá-lo depois disso. \n 4/5 -> Crítico: não pode esperar a release ou entrega do MVP acontecer, ou vamos nos arrepender amargamente por isso. \n 5/5 -> Muito crítico: não é um incidente, mas pode se tornar um em breve, ou; uma bola de neve incontrolável de retrabalho, se não ajustado o quanto antes. \n Resumo: Por não arrumarmos X, sofreremos Y. \n\n\ Insira um texto com detalhes não-técnicos aqui! \n\n *Critérios de Aceite:* \n\n- Logs (com level, timestamp, traceId etc) \n- Testes automatizados \n- Storybook \n- Documentação do repo (APIs e Arquitetura) atualizadas, se necessário \n- Infraestrutura como Código \n- Deploy para staging e production \n\n *Dúvidas:* \n\n- X \n\n *Referências:* \n\n- X"

  - trigger: ":jira-bug"
    replace: "*Descrição:* \n\n O problema X está acontecendo. \n\n *Passos p/ Reproduzir:* \n\n- X \n\n *Critérios de Aceite:* \n\n- Logs (com level, timestamp, traceId etc) \n- Testes automatizados, ao menos para cobrir o bug \n - Storybook \n- Documentação do repo (APIs e Arquitetura) atualizadas, se necessário \n- Infraestrutura como Código \n- Deploy para staging e production \n\n *Dúvidas:* \n\n- X \n\n *Referências:* \n\n- X"
