# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: ":shrug"
    replace: "¯\\_(ツ)_/¯"

  - trigger: ":code"
    replace: |-
      ```
      $|$
      ```

  - trigger: ":br-pr-suggestion"
    replace: |-
      > Pode resolver esta thread depois de ler. Fique a vontade de faze-la ou não!

      **Sugestão opcional:**
      
      X$|$

  - trigger: ":br-pr-compliment"
    replace: |-
      **Elogio:**
      
      X$|$
      
      > Pode resolve esta thread depois de ler

  - trigger: ":en-pr-suggestion"
    replace: |-
      > You can resolve this thread after reading it. Feel free to do it or not!

      **Optional suggestion:**
      
      X$|$

  - trigger: ":en-pr-compliment"
    replace: |-
      **Compliment:**
      
      X$|$
      
      > You can resolve this thread after reading it

  - trigger: ":br-jira-epic"
    replace: |-
      **PARA ATINGIR:** 
      
      - X$|$ 
      
      **ENTREGAREMOS:** 
      
      - X 
      
      **CRITÉRIOS DE ACEITE:** 
      
      Funcionais: 
      - X 
      
      Não-funcionais: 
      - X 
      
      **DÚVIDAS:** 
      
      - X 
      
      **REFERÊNCIAS:** 
      
      - X

  - trigger: ":en-jira-epic"
    replace: |-
      **TO ACHIEVE:** 
      
      - X$|$ 
      
      **WILL BE DELIVERED:** 
      
      - X 
      
      **ACCEPTANCE CRITERIA:** 
      
      Functionals: 
      - X 
      
      Non-functionals: 
      - X 
      
      **QUESTIONS:** 
      
      - X 
      
      **REFERENCES:** 
      
      - X

  - trigger: ":br-jira-story"
    replace: |-
      Eu, como X, quero conseguir Y para Z. 
      
      **CRITÉRIOS DE ACEITE:** 
      
      Funcionais: 
      - X 
      
      Não-funcionais: 
      - X 
      
      **DÚVIDAS:** 
      
      - X 
      
      **REFERÊNCIAS:** 
      
      - X

  - trigger: ":en-jira-story"
    replace: |-
      I, as a X, want to Y for Z. 
      
      **ACCEPTANCE CRITERIA:** 
      
      Funcionals: 
      - X 
      
      Non-funcionals: 
      - X 
      
      **QUESTIONS:** 
      
      - X 
      
      **REFERENCES:** 
      
      - X

  - trigger: ":br-jira-spike"
    replace: |-
      **O QUE QUEREMOS?** 
      
      - X$|$ 
      
      **POR QUE QUEREMOS?** 
      
      - X 
      
      **CRITÉRIOS DE ACEITE:** 
      
      Funcionais: 
      - X 
      
      Não-funcionais: 
      - X 
      
      **TIMEBOX MÁXIMO:** 
      
      X dias. 
      
      Passado esse tempo, recomenda-se encerrar o spike com o que se descobriu até então. Logo após, defina os próximos spikes junto ao time para dar continuidade à investigação. 
      
      **OUTPUT:** 
      
      - Decisão tomada 
      - Doc no Confluence ou repo 
      - Apresentação ao time 
      - Cards no Jira para endereçar os próximos passos 
      
      **DÚVIDAS:** 
      
      - X 
      
      **REFERÊNCIAS:** 
      
      - X

  - trigger: ":en-jira-spike"
    replace: |-
      **WHAT DO WE WANT?** 
      
      - X$|$ 
      
      **WHY DO WE WANT?** 
      
      - X 
      
      **ACCEPTANCE CRITERIA:** 
      
      Functionals: 
      - X 
      
      Non-functionals: 
      - X 
      
      **MAXIMUM TIMEBOX:** 
      
      X days. 

      Passed this time, we suggest closing the spike with the findings until now. Then, define the next steps together with the team to continue the investigation in a next spike.
      
      **OUTPUT:** 
      
      - Decision made
      - Doc in Confluence or repo
      - Presentation to team
      - Cards on Jira to address the next steps
      
      **QUESTIONS:** 
      
      - X 
      
      **REFERENCES:** 
      
      - X

  - trigger: ":br-jira-task"
    replace: |-
      **CRITÉRIOS DE ACEITE:** 
      
      Funcionais: 
      - X 
      
      Não-funcionais: 
      - Logs (com level, timestamp, traceId etc) 
      - Testes automatizados 
      - Storybook 
      - Documentação do repo (APIs e Arquitetura) atualizadas, se necessário 
      - Infraestrutura como Código 
      - Deploy para staging e production 
      
      **DÚVIDAS:** 
      
      - X 
      
      **REFERÊNCIAS:** 
      
      - X

  - trigger: ":en-jira-task"
    replace: |-
      **ACCEPTANCE CRITERIA:** 
      
      Funcionals: 
      - X 
      
      Non-funcional: 
      - Logs (with level, timestamp, traceId etc) 
      - Automated tests
      - Storybook 
      - Updated doc on repo (APIs and Architecture), if necessary
      - Infrastructure as Code
      - Deploy to staging and production 
      
      **QUESTIONS:** 
      
      - X 
      
      **REFERENCES:** 
      
      - X

  - trigger: ":br-jira-improvement"
    replace: |-
      **RELEVÂNCIA**: 
      
      1/4 -> Pouco ganho, muito esforço: provavelmente não deveria ser feito, exceto caso nada de mais relevante esteja pendente. 
      
      2/4 -> Muito ganho, muito esforço: deve ser priorizado eventualmente, se inovação é um aspecto importante na equipe. Se possível, fatie esta melhoria em micro-melhorias de 'pouco ganho, pouco esforço' para aumentar as chances dessa melhoria ser implementada. 
      
      3/4 -> Pouco ganho, pouco esforço: por custar pouco, pode ser priorizado para completar as sprints, desde que não haja bugs ou débitos pendentes (e que podem ser priorizados). 
      
      4/4 -> Muito ganho, pouco esforço: deveria ser priorizado assim que possível, mesmo que existam bugs ou débitos pendentes, uma vez que irá aumentar (e muito) a eficiência de um processo ou solução com um baixo esforço. 
      
      **RESUMO:** 
      
      Descreva a dor e o porquê a melhoria é necessária. 
      
      **IMPACTO:**
      
      Com esse ajuste esperamos os seguintes ganhos: 
      - X 
      
      **CRITÉRIOS DE ACEITE:** 
      
      Funcionais: 
      - X 
      
      Não-funcionais: 
      - Logs (com level, timestamp, traceId etc) 
      - Testes automatizados 
      - Storybook 
      - Documentação do repo (APIs e Arquitetura) atualizadas, se necessário 
      - Infraestrutura como Código 
      - Deploy para staging e production 
      
      **DÚVIDAS:** 
      
      - X 
      
      **REFERÊNCIAS:** 
      
      - X

  - trigger: ":en-jira-improvement"
    replace: |-
      **RELEVANCE**: 
      
      1/4 -> Low gain, high effort: probably shouldn't be done, unless nothing more relevant is pending. 
      
      2/4 -> High gain, high effort: it should eventually be prioritized, if innovation is an important aspect in the team. If possible, slice this improvement into 'low gain, low effort' micro-improvements to increase the chances of this improvement being implemented.
      
      3/4 -> Low gain, low effort: can be prioritized to complete sprints, as long as there are no outstanding bugs or delays (that can be prioritized).
      
      4/4 -> High gain, low effort: it should be prioritized as soon as possible, even if there are bugs or pending debts, since it will increase (by a lot) the efficiency of a process or solution with a low effort.
      
      **RESUME:** 
      
      Describe the pain points and why it's necessary.
      
      **IMPACT:**
      
      After adjusting it, we expect the following gains:
      - X 
      
      **ACCEPTANCE CRITERIA:** 
      
      Funcionals: 
      - X 
      
      Non-funcional: 
      - Logs (with level, timestamp, traceId etc) 
      - Automated tests
      - Storybook 
      - Updated doc on repo (APIs and Architecture), if necessary
      - Infrastructure as Code
      - Deploy to staging and production 
      
      **QUESTIONS:** 
      
      - X 
      
      **REFERENCES:** 
      
      - X

  - trigger: ":br-jira-debt"
    replace: |-
      **CRITICIDADE**: 

      1/4 -> Criticidade baixa, alto esforço: não é uma melhoria, pois já deveria ter sido feito, mas precisa ser ajustado para manter o código limpo e fácil de ser extendido. Se possível, fatie este débito em micro-débitos de 'baixo risco, baixo esforço' para aumentar as chances desse débito ser endereçado.

      2/4 -> Criticidade baixa, baixo esforço: pode ser priorizado depois de uma release importante ou MVP, mas deveria ser priorizado antes da próxima entrega acontecer.

      3/4 -> Criticidade alta, alto esforço: não é um incidente, mas pode se tornar um em breve, ou; uma bola de neve incontrolável de retrabalho, se não ajustado o quanto antes. Não pode esperar a release our entrega do MVP acontecer. Crie um épico para essa iniciativa e seja incisivo com business para priorizá-lo assim que possível.

      4/4 -> Criticidade alta, baixo esforço: não é um incidente, mas pode se tornar um em breve, ou; uma bola de neve incontrolável de retrabalho, se não ajustado o quanto antes. Priorize assim que possível.
      
      **RESUMO:** 
      
      Por não arrumarmos X, sofreremos Y. 
      
      Insira um texto com detalhes não-técnicos aqui! 
      
      **IMPACTO:** 
      
      X 

      **CRITÉRIOS DE ACEITE:** 
      
      Funcionais: 
      - X 
      
      Não-funcionais: 
      - Logs (com level, timestamp, traceId etc) 
      - Testes automatizados 
      - Storybook 
      - Documentação do repo (APIs e Arquitetura) atualizadas, se necessário 
      - Infraestrutura como Código 
      - Deploy para staging e production 
      
      **DÚVIDAS:** 
      
      - X 
      
      **REFERÊNCIAS:** 
      
      - X

  - trigger: ":en-jira-debt"
    replace: |-
      **RISK**: 

      1/4 -> Low risk, high effort: not an improvement as it already should have been done, but need to be done to keep the code clean and easy to extend. If possible, slice this debt into 'low risk, low effort' micro-debts to increase the chances of this debt being addressed.

      2/4 -> Low risk, low effort: can be prioritized after a major release or MVP, but should be prioritized before the next release happens.

      3/4 -> High risk, high effort: Not an incident, but could become one soon, or; an uncontrollable snowball of rework if not fixed as soon as possible. Can't wait for the MVP release or delivery to happen. Create an epic for this initiative and be aggressive with business to prioritize it as soon as possible.

      4/4 -> High risk, low effort: Not an incident, but could become one soon, or; an uncontrollable snowball of rework if not fixed as soon as possible. Prioritize as soon as possible.

      **SUMMARY:**

      By not fixing X, we will suffer Y.

      Insert text with non-technical details here!

      **IMPACT:**

      X

      **ACCEPTANCE CRITERIA:**

      Functionals:
      - X

      Non-functionals:
      - Logs (with level, timestamp, traceId etc)
      - Automated tests
      - Storybook
      - Updated repo documentation (APIs and Architecture) if needed
      - Infrastructure as Code
      - Deploy for staging and production

      **QUESTIONS:**

      - X

      **REFERENCES:**

      - X

  - trigger: ":br-jira-bug"
    replace: |-
      **DESCRIÇÃO:** 
      
      O problema X está acontecendo. 
      
      **PASSOS P/ REPRODUZIR:** 
      
      - X$|$ 
      
      **CRITÉRIOS DE ACEITE:** 
      
      - Logs (com level, timestamp, traceId etc) 
      - Testes automatizados, ao menos para cobrir o bug 
      - Storybook 
      - Documentação do repo (APIs e Arquitetura) atualizadas, se necessário 
      - Infraestrutura como Código 
      - Deploy para staging e production 
      
      **DÚVIDAS:** 
      
      - X 
      
      **REFERÊNCIAS:** 
      
      - X

  - trigger: ":en-jira-bug"
    replace: |-
      **PROBLEM DESCRIPTION:** 
      
      Problem X is happening.
      
      **STEPS TO REPRODUCE:** 
      
      - X$|$ 
      
      **ACCEPTANCE CRITERIA:** 
      
      - Logs (with level, timestamp, traceId etc) 
      - Automated tests, at least for covering the bug
      - Storybook
      - Updated repo documentation (APIs and Architecture) if needed
      - Infrastructure as Code
      - Deploy for staging and production

      **QUESTIONS:**

      - X

      **REFERENCES:**

      - X

  - trigger: ":en-use-case"
    replace: |-
      **Title:** UC1 - Place an order
      **Actor:** Buyer

      **Preconditions:**
      1. User is logged
      2. X

      **Flow of Events:**
      1. The customer browses the product catalog.
      2. The customer adds desired products to the shopping cart.
      3. The customer proceeds to checkout.
      4. The customer enters shipping information.
      5. The customer selects a payment method and completes payment.
      6. The system confirms the order and provides an order number.
      7. X

      **Postconditions:**
      1. Order is placed and visible to user
      2. X

  - trigger: ":en-test-case"
    replace: |-
      **Title:** UC1.TC1 - Verify Order Placement
      **Actor:** Buyer

      **Description:**
      Verify that a customer can successfully place an order.

      **Preconditions:**
      1. User is logged
      2. X

      **Test Steps:**
      1. Customer click on header "XPTO"
      2. Customer checks a paragraph containing "XPTO" existsd
      3. X

      **Postconditions:**
      1. Order is placed and visible to user
      2. X
