# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: ":shrug"
    replace: "¯\\_(ツ)_/¯"

  - trigger: ":meet"
    replace: "https://meet.google.com/ena-qpcg-ius?authuser=1"

  - trigger: ":pr-suggestion"
    replace: |-
      **Sugestão Opcional:**
      
      X$|$
      
      > Pode resolver essa thread quando preferir!

  - trigger: ":pr-compliment"
    replace: |-
      **Elogio:**
      
      X$|$
      
      > Pode resolver essa thread depois de ler!

  - trigger: ":jira-epic"
    replace: |-
      **PARA ATINGIR:** 
      
      - X$|$ 
      
      **ENTREGAREMOS:** 
      
      - X 
      
      **CRITÉRIOS DE ACEITE:** 
      
      Funcionais: 
      - X 
      
      Não-funcionais: 
      - X 
      
      **DÚVIDAS:** 
      
      - X 
      
      **REFERÊNCIAS:** 
      
      - X

  - trigger: ":jira-story"
    replace: |-
      Eu, como X, quero conseguir Y para Z. 
      
      **CRITÉRIOS DE ACEITE:** 
      
      Funcionais: 
      - X 
      
      Não-funcionais: 
      - X 
      
      **DÚVIDAS:** 
      
      - X 
      
      **REFERÊNCIAS:** 
      
      - X

  - trigger: ":jira-spike"
    replace: |-
      **O QUE QUEREMOS?** 
      
      - X$|$ 
      
      **POR QUE QUEREMOS?** 
      
      - X 
      
      **CRITÉRIOS DE ACEITE:** 
      
      Funcionais: 
      - X 
      
      Não-funcionais: 
      - X 
      
      **TIMEBOX MÁXIMO:** 
      
      X dias. 
      
      Passado esse tempo, recomenda-se encerrar o spike com o que se descobriu até então. Logo após, defina os próximos spikes junto ao time para dar continuidade à investigação. 
      
      **OUTPUT:** 
      
      - Decisão tomada 
      - Doc no Confluence ou repo 
      - Apresentação ao time 
      - Cards no Jira para endereçar os próximos passos 
      
      **DÚVIDAS:** 
      
      - X 
      
      **REFERÊNCIAS:** 
      
      - X

  - trigger: ":jira-task"
    replace: |-
      **CRITÉRIOS DE ACEITE:** 
      
      Funcionais: 
      - X 
      
      Não-funcionais: 
      - Logs (com level, timestamp, traceId etc) 
      - Testes automatizados 
      - Storybook 
      - Documentação do repo (APIs e Arquitetura) atualizadas, se necessário 
      - Infraestrutura como Código 
      - Deploy para staging e production 
      
      **DÚVIDAS:** 
      
      - X 
      
      **REFERÊNCIAS:** 
      
      - X

  - trigger: ":jira-improvement"
    replace: |-
      **RELEVÂNCIA**: 
      
      1/4 -> Pouco ganho, muito esforço: provavelmente não deveria ser feito, exceto caso nada de mais relevante esteja pendente. 
      
      2/4 -> Muito ganho, muito esforço: deve ser priorizado eventualmente, se inovação é um aspecto importante na equipe. Se possível, fatie esta melhoria em micro-melhorias de 'pouco ganho, pouco esforço' para aumentar as chances dessa melhoria ser implementada. 
      
      3/4 -> Pouco ganho, pouco esforço: por custar pouco, pode ser priorizado para completar as sprints, desde que não haja bugs ou débitos pendentes (e que podem ser priorizados). 
      
      4/4 -> Muito ganho, pouco esforço: deveria ser priorizado assim que possível, mesmo que existam bugs ou débitos pendentes, uma vez que irá aumentar (e muito) a eficiência de um processo ou solução com um baixo esforço. 
      
      **RESUMO:** 
      
      Descreva a dor e o porquê a melhoria é necessária. 
      
      **IMPACTO:**
      
      Com esse ajuste esperamos os seguintes ganhos: 
      - X 
      
      **CRITÉRIOS DE ACEITE:** 
      
      Funcionais: 
      - X 
      
      Não-funcionais: 
      - Logs (com level, timestamp, traceId etc) 
      - Testes automatizados 
      - Storybook 
      - Documentação do repo (APIs e Arquitetura) atualizadas, se necessário 
      - Infraestrutura como Código 
      - Deploy para staging e production 
      
      **DÚVIDAS:** 
      
      - X 
      
      **REFERÊNCIAS:** 
      
      - X

  - trigger: ":jira-debt"
    replace: |-
      **CRITICIDADE**: 
      
      1/5 -> Não crítico: não é uma melhoria, pois já deveria ter sido feito, mas precisa ser ajustado para manter o código limpo e fácil de ser extendido. 
      
      2/5 -> Criticidade baixa: pode ser priorizado depois de uma release importante ou MVP, mas deveria ser priorizado antes da próxima entrega acontecer. 
      
      3/5 -> Criticidade média: até pode esperar uma release importante ou entrega do MVP, mas vai custar bem mais caro ajustá-lo depois disso. 
      
      4/5 -> Crítico: não pode esperar a release ou entrega do MVP acontecer, ou vamos nos arrepender amargamente por isso. 
      
      5/5 -> Muito crítico: não é um incidente, mas pode se tornar um em breve, ou; uma bola de neve incontrolável de retrabalho, se não ajustado o quanto antes. 
      
      **RESUMO:** 
      
      Por não arrumarmos X, sofreremos Y. 
      
      Insira um texto com detalhes não-técnicos aqui! 
      
      **IMPACTO:** 
      
      X 

      **CRITÉRIOS DE ACEITE:** 
      
      Funcionais: 
      - X 
      
      Não-funcionais: 
      - Logs (com level, timestamp, traceId etc) 
      - Testes automatizados 
      - Storybook 
      - Documentação do repo (APIs e Arquitetura) atualizadas, se necessário 
      - Infraestrutura como Código 
      - Deploy para staging e production 
      
      **DÚVIDAS:** 
      
      - X 
      
      **REFERÊNCIAS:** 
      
      - X

  - trigger: ":jira-bug"
    replace: |-
      **DESCRIÇÃO:** 
      
      O problema X está acontecendo. 
      
      **PASSOS P/ REPRODUZIR:** 
      
      - X$|$ 
      
      **CRITÉRIOS DE ACEITE:** 
      
      - Logs (com level, timestamp, traceId etc) 
      - Testes automatizados, ao menos para cobrir o bug 
      - Storybook 
      - Documentação do repo (APIs e Arquitetura) atualizadas, se necessário 
      - Infraestrutura como Código 
      - Deploy para staging e production 
      
      **DÚVIDAS:** 
      
      - X 
      
      **REFERÊNCIAS:** 
      
      - X

  - trigger: ":mmd-header"
    replace: "%%{init: {'sequence': {'showSequenceNumbers': true} }}%%"

  - trigger: ":mmd-sequence"
    replace: |-
      sequenceDiagram
        participant t as TO
        participant d as DO

        t->>d: X
